apiVersion: v1
kind: ConfigMap
metadata:
  name: lab4-configmap
  labels:
    app: lab4
data:
  username: wildmaus
  company-name: itmo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab4-deployment
  labels:
    app: lab4
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab4
  template:
    metadata:
      labels:
        app: lab4
    spec:
      containers:
      - name: lab4
        image: ifilyaninitmo/itdt-contained-frontend:master
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_USERNAME
          valueFrom:
            configMapKeyRef:
              name: lab4-configmap
              key: username
        - name: REACT_APP_COMPANY_NAME
          valueFrom:
            configMapKeyRef:
              name: lab4-configmap
              key: company-name
---
apiVersion: v1
kind: Service
metadata:
  name: lab4-service
spec:
  selector:
    app: lab4
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000